Add reporting
zarathustra323/fortnight-app pull request #1
Opened 2018-06-29 15:15 UTC by solocommand

Adds campaign summary and creative breakdown reports, a few helpers/components, and the froala editor license key. Requires zarathustra323/fortnight-graph#1

![nativex 1](https://user-images.githubusercontent.com/1778222/42100236-4568823a-7b85-11e8-8aa5-7d174c4c9689.png)
![nativex](https://user-images.githubusercontent.com/1778222/42100237-457ecd4c-7b85-11e8-881b-18b768bd5db9.png)

2018-06-29 15:25 UTC, zarathustra323 requested changes

2018-06-29 15:25 UTC, zarathustra323 commented on app/controllers/portal/campaigns/manage/report/creative-breakdown.js
> +  publisherLogo: computed('campaign.criteria.placements.[]', function() {
Could the publisher just be queried?

2018-06-29 15:25 UTC, zarathustra323 commented on app/controllers/portal/campaigns/manage/report/summary.js
> +  publisherLogo: computed('campaign.criteria.placements.[]', function() {
Same as above...

2018-06-29 15:25 UTC, zarathustra323 commented on app/controllers/portal/campaigns/manage/report/summary.js
> +  ctr: computed('impressions', 'clicks', function() {
Actually, a lot of this file looks duplicated... any chance it could be consolidated?

2018-06-29 15:25 UTC, zarathustra323 commented on app/gql/queries/reports/campaign/creative-breakdown.graphql
> +    views
Is there not an ID for this "model?"

2018-06-29 15:25 UTC, zarathustra323 commented on app/helpers/compute-it.js
> +export function computeIt([lvalue, operator, rvalue]) {
https://www.npmjs.com/package/ember-math-helpers
?

2018-06-29 15:25 UTC, zarathustra323 commented on app/routes/portal/campaigns/manage/report/creative-breakdown.js
> +    this.controllerFor('portal.campaigns.manage.report.creative-breakdown').set('campaign', model.campaign);
Use `this.controllerFor(this.get('routeName'))` instead

2018-06-29 15:25 UTC, zarathustra323 commented on app/routes/portal/campaigns/manage/report/summary.js
> +    this.controllerFor('portal.campaigns.manage.report.summary').set('campaign', model.campaign);
Use `routeName`, as above

2018-06-29 15:25 UTC, zarathustra323 commented on app/routes/portal/campaigns/manage/report/summary.js
> +    const advertiserId = model.advertiser.id;
You can get the advertiser via `this.modelFor('portal')`
Likely more reliable

2018-06-29 15:25 UTC, zarathustra323 commented on app/routes/portal/campaigns/manage/report/creative-breakdown.js
> +    const advertiserId = model.advertiser.id;
You can get the advertiser via `this.modelFor('portal')`
Likely more reliable

2018-06-29 15:25 UTC, zarathustra323 commented on app/templates/components/-report/creative-card.hbs
> +        <img src="{{ creative.image.src }}?w=640&h=360&crop=focalPoint&fit=crop&dpr=1&fp-x={{ creative.image.focalPoint.x }}&fp-y={{ creative.image.focalPoint.y }}"
A new `imgix` component should be created for imgix parameters

2018-06-29 15:25 UTC, zarathustra323 commented on app/templates/components/high-charts.hbs
> +{{outlet}}
Unnecessary

2018-06-29 15:25 UTC, zarathustra323 commented on app/templates/manage/campaign/summary.hbs
> +    {{#link-to "portal.campaigns.manage.report.summary" model.advertiser.hash model.hash target="_blank" rel="noopener noreferrer"}}Report: Summary{{/link-to}}
You do not need to send the advertiser and campaign parameters

2018-06-29 15:25 UTC, zarathustra323 commented on app/templates/manage/campaign/summary.hbs
> +    {{#link-to "portal.campaigns.manage.report.creative-breakdown" model.advertiser.hash model.hash target="_blank" rel="noopener noreferrer"}}Report: Creative Breakdown{{/link-to}}
You do not need to send the advertiser and campaign parameters

2018-06-29 15:36 UTC, solocommand commented on app/gql/queries/reports/campaign/creative-breakdown.graphql
> +    views
There isn't -- it's essentially wrapping the `CampaignCreative` with additional delivery statistics. So the id would be `creative.id` essentially.

2018-06-29 16:01 UTC, solocommand commented on app/templates/manage/campaign/summary.hbs
> +    {{#link-to "portal.campaigns.manage.report.creative-breakdown" model.advertiser.hash model.hash target="_blank" rel="noopener noreferrer"}}Report: Creative Breakdown{{/link-to}}
Yeah it does -- this is on the /manage side not /portal

2018-06-29 16:21 UTC, zarathustra323 requested changes

2018-06-29 16:21 UTC, zarathustra323 commented on app/components/imgix-image.js
> +    const { x, y } = focalPoint;
focalPoint could be null, which would throw a `cannot destructure value` error

2018-07-02 13:38 UTC, zarathustra323 approved these changes

2018-07-02 13:38 UTC, merged